name: Build & Sync Packages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    container: lopsided/archlinux:latest

    steps:
      - name: Install tools
        shell: bash
        run: |
          echo Hello World
